version: '3.1'

services:
  portfolio_db:
    container_name: portfolio_db
    image: postgres:latest
    volumes:
      - ./portfolio_backend/portfolio_volume:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - portfolio_network
    environment:
        POSTGRES_PASSWORD: waspasswordtooshort!?
    restart: always
  
  portfolio_api:
    container_name: portfolio_api
    build:
      context: ./portfolio_backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - portfolio_network
    depends_on:
      - portfolio_db

  portfolio_ui:
    container_name: portfolio_ui
    build:
      context: ./portfolio_frontend
      dockerfile: ./Dockerfile
    ports:
      - "81:80"
    networks:
      - portfolio_network
    depends_on:
      - portfolio_api

networks:
  portfolio_network:
    driver: bridge
 