version: '3.1'

services:
  portfolio_db:
    container_name: portfolio_db
    image: postgres:latest
    volumes:
      - ./portfolio_volume:/var/lib/postgresql/data
    ports:
        - "5434:5432"
    environment:
        POSTGRES_PASSWORD: waspasswordtooshort!?
    restart: always
  
  portfolio_api:
    container_name: portfolio_api
    image: portfolio_backend:v1.0.0
    ports:
      - "8080:8000"
    depends_on:
      - portfolio_db

  portfolio_ui:
    container_name: portfolio_ui
    image: portfolio_frontend:v1.0.0
    ports:
      - "88:80"
    depends_on:
      - portfolio_api

 