# Generated by Django 5.1.2 on 2024-10-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skill',
            new_name='skills',
        ),
    ]
